services:
  localstack:
    image: localstack/localstack:4
    networks:
      - hmpps
    container_name: localstack-data-domain
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sns,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${TMPDIR:-/tmp/localstack}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:18
    container_name: adda-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=adda_user
      - POSTGRES_PASSWORD=adda_psw
      - POSTGRES_DB=adda_db
    volumes:
      - adda-postgres-data-api:/var/lib/postgresql

volumes:
  adda-postgres-data-api:

networks:
  hmpps:
