hmpps-auth:
  url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adda_db
    username: adda_user
    password: adda_psw

hmpps.sqs:
  useWebToken: false
  provider: localstack
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domainevents
  queues:
    adda-domain-events-queue:
      queueName: adda_domain_events_queue
      dlqName: adda_domain_events_dlq
      subscribeTopicId: domainevents
      subscribeFilter: '{"eventType":["adda.proposed.accommodation.approved", "adda.proposed.accommodation.unapproved"]}'

