hmpps-auth:
  url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

server:
  port: 9010

logging:
  level:
    org:
      flywaydb: DEBUG

service:
  probation-integration-delius:
    base-url: https://approved-premises-and-oasys-dev.hmpps.service.justice.gov.uk
  core-person-record:
    base-url: https://hmpps-person-record-dev.hmpps.service.justice.gov.uk

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adda_db
    username: adda_user
    password: adda_psw

hmpps.sqs:
  useWebToken: false
  provider: localstack
  topics:
    hmpps-domain-event-topic:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps-domain-event-topic
  queues:
    adda-domain-events-queue:
      queueName: adda_domain_events_queue
      dlqName: adda_domain_events_dlq
      subscribeTopicId: hmpps-domain-event-topic
      subscribeFilter: '{"eventType":["cpr.proposed.accommodation.update"]}'