hmpps-auth:
  url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sas_db
    username: sas_user
    password: sas_psw
