generic-service:
  nameOverride: hmpps-accommodation-data-domain-api
  productId: "HMPPS554" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-accommodation-data-domain-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-accommodation-data-domain-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    adda-domain-events-queue-secret:
      HMPPS_SQS_QUEUES_ADDA-DOMAIN-EVENTS-QUEUE_QUEUENAME: "QUEUE_NAME"
    adda-domain-events-dlq-secret:
      HMPPS_SQS_QUEUES_ADDA-DOMAIN-EVENTS-QUEUE_DLQNAME: "QUEUE_NAME"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPS-DOMAIN-EVENT-TOPIC_ARN: "TOPIC_ARN"
    hmpps-accommodation-data-domain-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-accommodation-data-domain-api:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-ID: "SYSTEM_CLIENT_ACCOMMODATION_DATA_DOMAIN_CLIENT_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-SECRET: "SYSTEM_CLIENT_ACCOMMODATION_DATA_DOMAIN_CLIENT_SECRET"
    accommodation-data-domain-rds-instance-output:
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"
      DB_NAME: "database_name"
      DB_ENDPOINT: "rds_instance_endpoint"
  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-accommodation-data-domain-api