---
# Per environment values which override defaults in hmpps-accommodation-data-domain-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: accommodation-data-domain-api-preprod.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: preprod
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises
